// Auto-generated by scripts/generate_config.sh — DO NOT EDIT.
// Source of truth: .env (gitignored)

enum SupabaseConfig {
    static let projectURL = "https://gsvjlyiszplcagwvphor.supabase.co"
    static let anonKey    = "sb_publishable_el5i30WNEFPwXosJlb0YcA_ohlm7gmJ"
    static let tableName  = "scam_messages"
}
