#!/usr/bin/env bash
# Reads .env from the project root and generates SupabaseConfig.swift.
# Add this as a Run Script Build Phase in Xcode (before Compile Sources):
#
#   "${SRCROOT}/scripts/generate_config.sh"
#
# The generated file is gitignored — never commit it.

set -euo pipefail

ENV_FILE="${SRCROOT}/.env"
OUTPUT_FILE="${SRCROOT}/MinamisumaCapitalOne/Config/SupabaseConfig.swift"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: .env file not found at ${ENV_FILE}. Copy .env.example to .env and fill in your values."
  exit 1
fi

# Load variables from .env (ignore comments and blank lines)
while IFS='=' read -r key value; do
  [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
  export "$key"="$value"
done < "$ENV_FILE"

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<SWIFT
// Auto-generated by scripts/generate_config.sh — DO NOT EDIT.
// Source of truth: .env (gitignored)

enum SupabaseConfig {
    static let projectURL = "${SUPABASE_PROJECT_URL}"
    static let anonKey    = "${SUPABASE_ANON_KEY}"
    static let tableName  = "${SUPABASE_TABLE_SCAM_MESSAGES}"
}
SWIFT

echo "✓ SupabaseConfig.swift generated."
